version: '3.4'

services:

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
 
  basketdb:
      container_name: basketdb
      restart: always
      ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1434:1433"
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@polycart.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  polycart.catalog.api:
    container_name: polycart.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" 
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  polycart.basket.api:
    container_name: polycart.basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://polycart.discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672" 
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - basketdb
      - rabbitmq 
    ports:
      - "8001:80"

  polycart.discount.api:
    container_name: polycart.discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200" 
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  polycart.discount.grpc:
    container_name: polycart.discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  polycart.ordering.api:
    container_name: polycart.ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;TrustServerCertificate=true"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672" 
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - orderdb
      - rabbitmq 
    ports:
      - "8004:80"

  polycart.ocelot.apigateway:
    container_name: polycart.ocelot.apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - polycart.catalog.api
        - polycart.basket.api
        - polycart.discount.api
        - polycart.ordering.api
    ports:
      - "8010:80"


  polycart.shopping.aggregator:
    container_name: polycart.shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://polycart.catalog.api"
      - "ApiSettings:BasketUrl=http://polycart.basket.api"
      - "ApiSettings:OrderingUrl=http://polycart.ordering.api"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - polycart.catalog.api
      - polycart.basket.api
      - polycart.ordering.api
    ports:
      - "8005:80"

  polycart.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://polycart.ocelot.apigateway"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - polycart.ocelot.apigateway
      - polycart.catalog.api
      - polycart.basket.api
      - polycart.discount.api
      - polycart.ordering.api
    ports:
      - "8006:80"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data   

  kibana:
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"  


  polycart.status.web:
    container_name: polycart.status.web
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
        - HealthChecksUI__HealthChecks__0__Uri=http://polycart.catalog.api/hc
        - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
        - HealthChecksUI__HealthChecks__1__Uri=http://polycart.basket.api/hc
        - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
        - HealthChecksUI__HealthChecks__2__Uri=http://polycart.discount.api/hc
        - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
        - HealthChecksUI__HealthChecks__3__Uri=http://polycart.ordering.api/hc
        - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
        - HealthChecksUI__HealthChecks__4__Uri=http://polycart.shopping.aggregator/hc
        - HealthChecksUI__HealthChecks__5__Name=AspnetRunBasics WebMVC Health Check
        - HealthChecksUI__HealthChecks__5__Uri=http://polycart.web/hc    
    ports:
        - "8007:80"

