version: '3.4'

services:

  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine
     
  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  polycart.catalog.api:
    image: ${DOCKER_REGISTRY-}polycartcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/PolyCart.Catalog.API/Dockerfile

  polycart.basket.api:
    image: ${DOCKER_REGISTRY-}polycartbasketapi
    build:
      context: .
      dockerfile: Services/Basket/PolyCart.Basket.API/Dockerfile

  polycart.discount.api:
    image: ${DOCKER_REGISTRY-}polycartdiscountapi
    build:
      context: .
      dockerfile: Services/Discount/PolyCart.Discount.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
